[package]
name = "git-radio"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.18"
image = "0.24"
clap = { version = "4.4", features = ["derive"] }
chrono = "0.4"
indicatif = { version = "0.17", features = ["rayon"] }
palette = "0.7"
rayon = "1.8"
rand = "0.8"
